# Generated by Django 4.0 on 2022-02-02 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodresys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='food_image',
        ),
    ]
