# Generated by Django 4.0 on 2022-02-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodresys', '0002_remove_transaction_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='food_in_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='food_in_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='food_out_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='food_out_time',
            field=models.CharField(max_length=50),
        ),
    ]
