# Generated by Django 4.0 on 2022-02-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodresys', '0003_alter_transaction_food_in_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempDonorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=50)),
                ('donor_phone_number', models.CharField(max_length=20)),
                ('food_name', models.CharField(max_length=100)),
                ('food_shelf_life', models.IntegerField()),
                ('food_m_date', models.DateField()),
                ('food_m_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TempReceiverData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=50)),
                ('receiver_phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
